//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBot {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Localize() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myBot._Localize", typeof(_Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add bot master に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddBotMaster {
            get {
                return ResourceManager.GetString("AddBotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add extension script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddExtesionScript {
            get {
                return ResourceManager.GetString("AddExtesionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddMessage {
            get {
                return ResourceManager.GetString("AddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   myBot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archived Messages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArchivedMessages {
            get {
                return ResourceManager.GetString("ArchivedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to disabling this bot? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AreYouSureToDisablingThisBot {
            get {
                return ResourceManager.GetString("AreYouSureToDisablingThisBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to enabling this bot? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AreYouSureToEnablingThisBot {
            get {
                return ResourceManager.GetString("AreYouSureToEnablingThisBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bot masters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BotMasters {
            get {
                return ResourceManager.GetString("BotMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change tweet timing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeTweetTiming {
            get {
                return ResourceManager.GetString("ChangeTweetTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to archive this message? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmArchiveMessage {
            get {
                return ResourceManager.GetString("ConfirmArchiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete this bot master? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDeleteBotMaster {
            get {
                return ResourceManager.GetString("ConfirmDeleteBotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete this message? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to restore this message? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmRestoreMessage {
            get {
                return ResourceManager.GetString("ConfirmRestoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionScripts {
            get {
                return ResourceManager.GetString("ExtensionScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduled Messages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScheduledMessages {
            get {
                return ResourceManager.GetString("ScheduledMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in with your Twitter account (not Bot account) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sign_in_with_Twitter {
            get {
                return ResourceManager.GetString("Sign_in_with_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignIn_Title {
            get {
                return ResourceManager.GetString("SignIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet timing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TweetTiming {
            get {
                return ResourceManager.GetString("TweetTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet while に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TweetWhile {
            get {
                return ResourceManager.GetString("TweetWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
